name: Task 2 - .NET API Tests CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      TEST_USER_EMAIL: "test@example.com"
      TEST_USER_PASSWORD: "password"
      BASE_URL: "http://localhost:5000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
  run: dotnet restore
  working-directory: Story

       - name: Build project
  run: dotnet build --configuration Release --no-restore
  working-directory: Story

- name: Run tests
  run: dotnet test --configuration Release --no-build
  working-directory: Story


