name: Task 2 - .NET API Tests CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      TEST_USER_EMAIL: "test@example.com"
      TEST_USER_PASSWORD: "password"
      BASE_URL: "http://localhost:5000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore Story.sln

      - name: Build solution
        run: dotnet build Story.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Story.sln --configuration Release --no-build



